### ISSUE TITLE
Header Image still missing in Example Site

### ISSUE THREAD

**Issue by onedrawingperday** [cboettig/hugo-now-ui#12]
Hi @cboettig 

I noticed that after your theme was updated, the header image is still missing.

In the config of the Example Site you need to change line 79 to:
` background = "img/bg11.jpg"`

Note that the forward slash has been deleted. Whenever a URL begins with a forward slash Hugo converts it into a link that is relative to the root of a site and `absURL` has no effect.

**Comment by onedrawingperday** [comment]
Hello again @cboettig 

Your theme was updated recently and now it's at the top of the Hugo Themes Showcase but images are still not loading in its demo: https://themes.gohugo.io/theme/hugo-now-ui/

Can you please look into it? For guidance also have a look at [Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) in the updated Hugo Themes README.

If you need any further help do not hesitate to ask.

Thanks.

CC / @digitalcraftsman

**Comment by cboettig** [comment]
@onedrawingperday @digitalcraftsman Thanks for the ping here.  Yes, I now use absolute URLs everywhere.  I think the problem comes from:

https://github.com/cboettig/hugo-now-ui/blob/3a9f45955c6e1bcf710981e875804bd57cd92936/layouts/_default/baseof.html#L11

**Comment by cboettig** [comment]
I'm not quite sure how to resolve this though.  As you can see, the above is getting rendered with as:

https://github.com/cboettig/hugo-now-ui/blob/3a9f45955c6e1bcf710981e875804bd57cd92936/docs/index.html#L112

note the background URL does not have the full URL to the image, despite the `absURL` pipe in the layout.  Any suggestions?

**Comment by onedrawingperday** [comment]
@cboettig 

Please change [Line 11 of hugo-now-ui/layouts/_default/baseof.html](https://github.com/cboettig/hugo-now-ui/blob/3a9f45955c6e1bcf710981e875804bd57cd92936/layouts/_default/baseof.html#L11) to the following:

```
<div class="page-header-image" data-parallax="true" style="background-image: url('{{ (.Param "background")  | (default "img/header.jpg" | absURL) }}');">
```

Basically you need to use the parentheses to group the `default` function with the `absURL` pipe so that the latter refers to `"img/header.jpg"`

Please do the above and let me know. Thanks.

**Comment by tom-mi** [comment]
The suggested (and unfortunately implemented) change in `baseof.html` breaks the `background` parameter.

You can observe the issue on the demo page when having a look at `landing` -- that page is supposed to have a different background, but doesn't: https://themes.gohugo.io//theme/hugo-now-ui/landing/

The correct grouping is
```
<div class="page-header-image" data-parallax="true" style="background-image: url('{{ (.Param "background" | default "img/header.jpg") | absURL) }}');">
```
On my machine, even the original version without parentheses does the right thing for both using the `background` parameter and relying on the default setting.

As far as I understand, the only change necessary was removing the leading slash from the default header image.

I'll open a pull request.

**Comment by cboettig** [comment]
Thanks @tom-mi , a PR would be great

**Comment by cboettig** [comment]
@onedrawingperday Would you be able to take a quick look at the proposed change in #30 and confirm it fixes and does not break the rendering of background images on the templates page? 

As this thread shows I've had a heck of a time getting consistent behavior for background image URLs across both gh-pages preview I host from this repo and the preview in the official themes, and I cannot easily check the latter.

**Comment by tom-mi** [comment]
I've used hugo version `0.57.2` for testing this, if that is of any help

**Comment by onedrawingperday** [comment]
@cboettig Actually the linked PR may serve the `.Params.background` of a content page like `landing` but when tested with the Themes Site Build Script it breaks the default banner in every other page that does not have such a parameter.

Currently it is the other way around. The default header is served but not the custom image parameter.

Instead of playing with the `default` function I suggest that you refactor this line to the following:

```
<div class="page-header-image" data-parallax="true" style="background-image: url('{{ with .Params.background }}{{ . | absURL }}{{ else }}{{ "img/header.jpg" | absURL }}{{ end }}');">
```
And that will take care of this issue.

P.S. I am currently busy so I will unsubscribe from this thread. If you need anything more then reach out in the Hugo Themes repository. Also feel free to close this issue.
