### ISSUE TITLE
best ways to modify this theme? 

### ISSUE THREAD

**Issue by titaniumbones** [cboettig/hugo-now-ui#15]
Hi @cboettig , thanks for this theme! I was wondering how best to modify colors and the like -- is there a standard bootstrap variables partial hiding here somewhere? THank you!

**Comment by cboettig** [comment]
You "just" have to edit and recompile the SASS variables, see: https://github.com/cboettig/hugo-now-ui/blob/master/static/sass/now-ui-kit/_variables.scss

**Comment by titaniumbones** [comment]
ah.  So would that be `sass --scss  sass/now-ui-kit.scss 
css/now-ui-kit.css`? I usually just use node-sass on other people's 
projects :-) .

**Comment by cboettig** [comment]
hehe, I look it up every time too.  Or `sass --watch sass:css` I think.

**Comment by cboettig** [comment]
Note that thanks to https://github.com/cboettig/hugo-now-ui/pull/22, you can now just modify variables.scss and hugo will automatically compile the SASS resources to css for you using the new hugo pipes! (More details in the PR notes if you're interested, but basically it should all 'just work' now).  Give it a spin!

**Comment by titaniumbones** [comment]
that's awesome -- I was looking at the sass pipes and thinking about implementing myself, excited to work with this!
