### ISSUE TITLE
errors on building a site with actual debian hugo version 0.47.1  

### ISSUE THREAD

**Issue by webconcept-one** [cboettig/hugo-now-ui#19]
I get errors on building a new site.
Minimum version is 0.18 so I should be good with 0.47.1

The output is:
```
ERROR 2018/12/17 17:27:04 Failed to add template "shortcodes/carousel.html" in path "shortcodes/carousel.html": template: shortcodes/carousel.html:14: unexpected "=" in operand
ERROR 2018/12/17 17:27:04 shortcodes/carousel.html : template: shortcodes/carousel.html:14: unexpected "=" in operand
Total in 50 ms
Error: Error building site: logged 2 error(s)
```

**Comment by webconcept-one** [comment]
I'm using the actual 0.52 git version now and do not have any issues anymore.

**Comment by cboettig** [comment]
thanks for the bug report and the follow up.  That short-code was recently contributed in a PR, I didn't then go back and test against older versions.  Guess we need to bump the minimum version!

**Comment by cboettig** [comment]
Thanks, I've bumped the minimum version in `theme.toml` as well now.
