### ISSUE TITLE
Theme Configuration: Getting started errors

### ISSUE THREAD

**Issue by alexsasharegan** [cboettig/hugo-now-ui#2]
New to hugo here, but adding your theme into my project throws a warning/error:

```
Unable to find archetypes directory for theme "hugo-now-ui" at "/my/hugo/site/themes/hugo-now-ui/archetypes"
```

I believe all that is needed here is to stub out the archetypes directory. Git works off files, so it won't commit an empty directory, so maybe just add a `.gitkeep` empty file to stub the directory structure out?

**Comment by cboettig** [comment]
hmm, not sure why that would be, I never see a warning about the theme not having an `archetypes` directory when I run `hugo`.  Can you point me to a minimal reproducible example?  

Your solution sounds fine; it just seems not ideal to have an archetypes directory when the theme isn't actually providing archetypes.

Though maybe it would make senes to include archetypes corresponding to the basic layouts shown in the example content?  (I've never found archetypes particularly useful, but perhaps I missing something or maybe I just don't make enough use of configuration in the yaml headers)...

**Comment by alexsasharegan** [comment]
You know what, this appears to have been a side-effect of missing configuration values. I started a new project to recreate the error, but things played out differently. The initial gotcha getting started with this theme is the required configuration variables.

To pivot this issue, it would be nice to have some documentation around your theme configuration. Obviously, the example site is plenty for me to go on, but it's an unfriendly way to get started seeing this error:

```
Started building sites ...
ERROR 2017/12/12 09:26:00 Error while rendering "taxonomyTerm": 
>  template: /Users/alex/github.com/alexsasharegan/hugo-now-ui-arch-ex/themes/hugo-now-ui/layouts/_default/terms.html:11:152: 
>  executing "/Users/alex/github.com/alexsasharegan/hugo-now-ui-arch-ex/themes/hugo-now-ui/layouts/_default/terms.html" at <relURL>: 
>  wrong number of args for relURL: want 1 got 0
```

I believe this error derives from a missing background image (then piping that to `relURL`).

**Comment by lorenae** [comment]
I have the same problem.
After executing the following commands
```
hugo new site mysite
cd mysite/themes
git clone https://github.com/cboettig/hugo-now-ui
cd ..
echo 'theme = "hugo-now-ui"' >> config.toml
hugo server -D
```
I receive this output

```
Started building sites ...
ERROR 2017/12/13 12:39:34 Error while rendering "taxonomyTerm": template: /Users/lorenae/dev/mysite/themes/hugo-now-ui/layouts/_default/terms.html:11:152: executing "/Users/lorenae/dev/mysite/themes/hugo-now-ui/layouts/_default/terms.html" at <relURL>: wrong number of args for relURL: want 1 got 0

Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
6 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 3 ms
Watching for changes in /Users/lorenae/dev/mysite/{data,content,layouts,themes,static}
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

what I'm doing wrong?
thanks
Lorena

**Comment by cboettig** [comment]
@lorenae Have you defined a background image in `config.toml`?  e.g.

https://github.com/cboettig/hugo-now-ui/blob/9f50ad37e56df2189a0902f4b7697dd95e3ada2e/exampleSite/config.toml#L74

**Comment by lorenae** [comment]
thanks @cboettig for your suggestion! I've missed that you have an example site

**Comment by alexsasharegan** [comment]
Yeah, I think a quick addition to documentation about config would help new users get up and running fast 👍 It would be nice to read how the menu items are set up too rather than just inferring it from the example site.

Thanks for the great theme!

**Comment by cboettig** [comment]
Thanks for the feedback.  I'm definitely open to pull requests on documentation or anything; often with fresh eyes you may have a better sense of what needs to be documented than me!  (I'm usually a skip-the-docs-and-play-with-the-example kind to be honest).  Otherwise I'll get around to updating docs when I get chance.

**Comment by alexsasharegan** [comment]
Fair enough! I'll see what I can put together when I get my next time block to work on the project using this! I'll close and maybe reference it via PR if I come up with some additions.
