### ISSUE TITLE
Mixed Content in Hugo Now UI Demo on Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [cboettig/hugo-now-ui#25]
Hello again @cboettig 

Earlier today the Hugo themes were updated on the website and your theme's demo is now loading almost everything: https://themes.gohugo.io/theme/hugo-now-ui/

There is just the following missing external image, that is also throwing a Mixed Content warning:

In theme/hugo-now-ui/components/index.html:

    Insecure img urls:
        http://demos.creative-tim.com/now-ui-kit/img/now-logo.png

Can you please look into replacing this broken URL with something else that is using `https`?

Thank you

ref: https://github.com/gohugoio/hugoThemes/issues/532

**Comment by cboettig** [comment]
Thanks! should be fixed now.
