### ISSUE TITLE
Now UI Kit pro

### ISSUE THREAD

**Issue by GIT-STATA** [cboettig/hugo-now-ui#26]
@cboettig 

It would be great if you could direct a way to use other creative-tim themes with HUGO - like the [Now UI Kit PRO Theme - Premium Bootstrap 4 UI Kit ](https://www.creative-tim.com/product/now-ui-kit-pro). 

**Is there any way to link to articles and write a documentation? I would really love to help with that as well!**

*Many many thanks for all of your great work!!!*

**Comment by cboettig** [comment]
The themes you are referring to are commercially licensed Pro themes, whereas this project is based on the MIT-licensed open source version Now UI Kit from Creative Tim.  Non-open-source material could not be provided in this manner, though of course anyone could use much the same strategy shown here to adapt the theme to hugo.  If you already have a license for one of the premium themes, you might consider contacting CreativeTim team technical support directly for advice on use with Hugo.  

Cheers,

**Comment by GIT-STATA** [comment]
Thank you so much for letting me know... I bought the Pro version... yes of course!

In general it would be great to outline how you would accomplish porting a bootstrap theme into HUGO...

Again, I will try to post all information I will get... out there in the www is little to nothing... maybe you could still help a little bit!? We will see... 
Best wishes! 
Thank you so much again!
