### ISSUE TITLE
Not really working...

### ISSUE THREAD

**Issue by azilber** [cboettig/hugo-now-ui#5]
I installed it, and it's not really working.  Might be related to ugly urls.  It doesn't seem like uglyurls = "true" is supported.

<img width="1366" alt="screen shot 2017-12-30 at 7 35 25 pm" src="https://user-images.githubusercontent.com/691270/34453843-ea71f958-ed98-11e7-8eb4-aed4dd00bb7f.png">

Second issue, mathjax cdn is gone, had to run the following across the theme:

find ./ -type f |xargs sed -i 's,cdn.mathjax.org/mathjax/latest,cdn.rawgit.com/mathjax/MathJax/2.7.1,g'

**Comment by JOduMonT** [comment]
I had this same kind of issue
and it's appear being in the archetype

but most of the time when I want to discover a theme, I just cut and past the '`exampleSite`' at the root as learn/build on top of it.

**Comment by cboettig** [comment]
Site now has more reasonable defaults out of the box.
