### ISSUE TITLE
Demo site: images/assets broken

### ISSUE THREAD

**Issue by MartinTheWanderer** [cboettig/hugo-now-ui#8]
Just started playing with this lovely theme - noticed the live demo is partially broken, e.g. images do not load and give a 404, e.g. 

`https://cboettig.github.io/hugo-now-ui/assets/img/landing.jpg 
or
https://cboettig.github.io/hugo-now-ui/assets/img/avatar.jpg`

Would look even better and more convincing if you fixed this... ;)

**Comment by cboettig** [comment]
Thanks, fixed now, sorry for the incredibly slow turn-around.

**Comment by jchillerup** [comment]
Some/all(?) of the JS/CSS assets are broken currently. The theme looks beautiful on the screenshot, though!

**Comment by cboettig** [comment]
@jchillerup 
should be fixed (again), thanks for the heads up!
